version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: ef_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: ef_db
    ports:
      - "${POSTGRES_PORT:-5433}:5432"
    volumes:
      - postgres_data_v2:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: ef_redis
    restart: always
    ports:
      - "${REDIS_PORT:-6379}:6379"

volumes:
  postgres_data_v2:
